### PR TITLE
Update require statement in RSpec example

### PR DESCRIPTION
**Pull request by t3ly**
Get a LoadError with
```
require 'ar-query-matcher'
```
Updated to
```
require 'ar_query_matcher'
```

### CODE REVIEW

**Comment by t3ly** [comment]
bors merge

**Comment by inoda** [comment]
Just ran into this as well! Seems like maybe @mzruya is the only one with merge privileges?

**Comment by mzruya** [comment]
Sorry, didn't know you can't merge. I'll look into the repo settings.

**Comment by mzruya** [comment]
@inoda, @t3ly. I updated the settings and gave "gusto/Developers" access to the master branch.

**Pull request merged**
